services:
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    env_file:
      - path: ./backend/.env
        required: true
    volumes:
      - ./data/db:/var/lib/postgresql/data/
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports: 
      - 5173:5173
    depends_on:
      - backend
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 3000:3000
    env_file:
      - path: ./backend/.env
        required: true
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate dev && npx prisma generate && npx prisma db seed && npm run dev"
  prisma:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: prisma-studio
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 5555:5555
    env_file:
      - path: ./backend/.env
        required: true
    depends_on:
      - backend
    command: >
      sh -c "npx prisma studio"
